version: '3.8'

services:
  # Backend API
  backend:
    build: ./backend
    container_name: sleepface-backend
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=production
      - MONGO_URL=mongodb+srv://mkrishnachaitanya21:mkrishnachaitanya@cluster0.mwnoez2.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      - DATABASE_NAME=sleepface
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - FIREBASE_PROJECT_ID=${FIREBASE_PROJECT_ID}
      - FIREBASE_PRIVATE_KEY_ID=${FIREBASE_PRIVATE_KEY_ID}
      - FIREBASE_PRIVATE_KEY=${FIREBASE_PRIVATE_KEY}
      - FIREBASE_CLIENT_EMAIL=${FIREBASE_CLIENT_EMAIL}
      - FIREBASE_CLIENT_ID=${FIREBASE_CLIENT_ID}
    # No local dependencies - uses MongoDB Atlas
    networks:
      - sleepface-network
    restart: unless-stopped

  # Frontend (React Native - for development)
  frontend:
    build: ./frontend
    container_name: sleepface-frontend
    ports:
      - "19006:19006"
    environment:
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
    networks:
      - sleepface-network
    depends_on:
      - backend

networks:
  sleepface-network:
    driver: bridge
